[build.environment]
DART_SASS_VERSION = "1.93.2"
GO_VERSION = "1.25.3"
HUGO_VERSION = "0.149.0"
NODE_VERSION = "22.20.0"
TZ = "Europe/Oslo"
HUGO_THEME = "hugo-arcana"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """